# Generated by Django 5.2 on 2025-04-26 06:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_date', models.DateField()),
                ('due_date', models.DateField()),
                ('principal_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_accrued', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.loan')),
            ],
        ),
        migrations.CreateModel(
            name='DuePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.billing')),
            ],
        ),
    ]
