# Generated by Django 5.2 on 2025-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_billing_duepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
